Internal state:
* endpoint-A
* endpoint-B
* A-endpoint-online
* B-endpoint-online
* A-thread-FSM
* B-thread-FSM

Input signals:

@startuml
[*] --> INIT

INIT --> OFFLINE : next
INIT : enter / setup A-thread-FSM
INIT : enter / setup B-thread-FSM

state GENERIC {
    GENERIC : enter / setup A-thread-FSM
    GENERIC : enter / setup B-thread-FSM

    [*] --> EMIT

    EMIT --> EMIT : discovery-timer / emit discovery-push for A,B
    EMIT : enter / setup discovery-timer

    --

    [*] --> PROXY

    PROXY --> PROXY : discovery / proxy to (A|B)-thread-FSM\ndiscovery-push proxy to (A|B)-thread-FSM

    --

    [*] --> CONSUME

    CONSUME --> CONSUME : isl-up / persist state\nisl-down / persist state
}

GENERIC --> MOVED : moved
GENERIC --> OFFLINE : offline / set (A|B)-endpoint-online = false

MOVED --> GENERIC : discovery
MOVED : ENTER / persist state

OFFLINE --> OFFLINE : isl-up / persist state\nisl-down / persist state
OFFLINE --> OFFLINE_SWITCH : online
OFFLINE --> OFFLINE_SWITCH : offline

state offlineGate <<choice>>

OFFLINE_SWITCH --> offlineGate : next
OFFLINE_SWITCH : enter / set (A|B)-endpoint-online = (true|false)

offlineGate --> OFFLINE : [!A-endpoint-online || !B-endpoint-online]
offlineGate --> GENERIC : [A-endpoint-online && B-endpoint-online]

@enduml
