@startuml
[*] --> UNKNOWN

UNKNOWN --> ADVANCE : isl-up
UNKNOWN --> WAIT : push-discovery
UNKNOWN --> DOWN : offline-fail-timer

ADVANCE --> READY : push-discovery
ADVANCE --> UNKNOWN : no-discovery-timer

WAIT --> READY : isl-up
WAIT --> DOWN : fail-timer
WAIT --> WAIT : push-discovery

READY --> WAIT : push-discovery
READY --> ADVANCE : isl-up
READY --> UNKNOWN : no-discovery-timer
@enduml
