Internal state:
* remote endpoint (swId + port) (initial not set)

Input signals:
* port-up
* port-down
* discovery-timer
* discovery
* discovery-pushed
* online
* offline

Output signals:
* isl-move
* force-down (?)
* physical-down
* discovery
* discovery-pushed
* online
* offline

@startuml
[*] --> INIT

INIT -r-> PREPOPULATE : history
INIT --> UNOPERATIONAL : offline
INIT --> OPERATIONAL : online

PREPOPULATE --> OPERATIONAL : online
PREPOPULATE --> UNOPERATIONAL : offline
PREPOPULATE : enter / set remote
PREPOPULATE : enter / emit isl-setup

state OPERATIONAL {
    OPERATIONAL : enter / emit online

    state discoveredChoice <<choice>>
    state movedChoice <<choice>>

    [*] --> UNKNOWN

    UNKNOWN --> DOWN : port-down
    UNKNOWN --> discoveredChoice : port-up

    DOWN --> discoveredChoice : port-up
    DOWN : enter / emit physical-down

    discoveredChoice --> UP : [remote is unset]
    discoveredChoice --> EXPECT_DISCOVERY : [remote is set]

    UP --> DOWN : port-down
    UP --> UP : discovery-timer / emit discovery-push
    UP --> movedChoice : discovery / set remote
    UP : enter / raise discovery-timer

    EXPECT_DISCOVERY --> movedChoice : discovery
    EXPECT_DISCOVERY --> DOWN : port-down
    EXPECT_DISCOVERY --> EXPECT_DISCOVERY : discovery-pushed / emit discovery-pushed

    movedChoice --> DISCOVERED : [remote not changed]
    movedChoice --> DISCOVERED : [remote changed] / emit isl-move,\nrecord remote,\nemit isl-setup

    DISCOVERED --> movedChoice : discovery
    DISCOVERED --> DISCOVERED : discovery-pushed / emit discovery-pushed
    DISCOVERED --> DOWN : port-down
    DISCOVERED : enter / emit discovery
}

OPERATIONAL --> UNOPERATIONAL : offline

UNOPERATIONAL --> OPERATIONAL : online
UNOPERATIONAL : enter / emit offline

@enduml
