Internal state:
* remote endpoint (swId + port) (initial not set)

Input signals:
* port-up
* port-down
* discovery-timer
* discovery
* discovery-pushed
* online
* offline

Output signals:
* isl-move
* force-down (?)
* physical-down
* discovery
* discovery-pushed
* online
* offline

@startuml
[*] --> INIT

INIT -r-> PREPOPULATE : history
INIT --> UNOPERATIONAL : offline
INIT --> OPERATIONAL : online

PREPOPULATE --> OPERATIONAL : online
PREPOPULATE --> UNOPERATIONAL : offline
PREPOPULATE : enter / set remote
PREPOPULATE : enter / emit isl-setup

state OPERATIONAL {
    OPERATIONAL : enter / emit online

    state discoveredChoice <<choice>>

    [*] --> UNKNOWN

    UNKNOWN --> DOWN : port-down
    UNKNOWN --> discoveredChoice : port-up

    UP -u-> DOWN : port-down
    UP --> UP : discovery-timer / emit discovery-push
    UP --> DISCOVERED : discovery / set remote
    UP : enter / raise discovery-timer

    DOWN --> discoveredChoice : port-up
    DOWN : enter / emit physical-down

    discoveredChoice --> UP : [remote is unset]
    discoveredChoice --> DISCOVERED : [remote is set]

    state DISCOVERED {
        state entryChoice <<choice>>
        state movedChoice <<choice>>

        [*] --> entryChoice

        entryChoice -> movedChoice : [is discovery]
        entryChoice --> MAIN : [is not discovery]
        
        movedChoice --> CONFIRM_DISCOVERY : [remote not changed]
        movedChoice -> MOVED : [remote changed]

        MAIN -> movedChoice : discovery
        MAIN --> MAIN : discovery-pushed / emit discovery-pushed

        MOVED --> CONFIRM_DISCOVERY : next
        MOVED : enter / emit isl-move
        MOVED : enter / record remote
        MOVED : enter / emit isl-setup

        CONFIRM_DISCOVERY --> MAIN : next
        CONFIRM_DISCOVERY : enter / emit discovery
    }
    DISCOVERED --> DOWN : port-down
}

OPERATIONAL --> UNOPERATIONAL : offline

UNOPERATIONAL --> OPERATIONAL : online
UNOPERATIONAL : enter / emit offline

@enduml
