Internal state:
* remote endpoint (swId + port) (initial not set)
* online (boolean) (initial true)

Input signals:
* port-up
* port-down
* port-managed
* port-unmanaged
* discovery-timer
* discovery
* discovery-pushed
* enable
* disable
* online
* offline

Output signals:
* discovery (proxy)
* isl-down
* isl-disable
* isl-move
* isl-push-fail (?)
* isl-unmanaged
* push-discovery

@startuml
[*] --> INIT

INIT -r-> PREPOPULATE : history
INIT --> BECOME_OFFLINE : offline
INIT --> OPERATIONAL : online

PREPOPULATE : enter / set remote
PREPOPULATE -l-> INIT : next

state OPERATIONAL {
    [*] --> UNKNOWN

    UNKNOWN --> DOWN : port-down
    UNKNOWN --> UP : port-up
    UNKNOWN : enter / set online true

    UP --> DOWN : port-down
    UP --> makeDiscovery : discovery-timer
    UP --> DISCOVERED : discovery

    makeDiscovery : enter / push-discovery
    makeDiscovery --> UP : next

    DOWN --> UP : port-up

    state DISCOVERED {
        DISCOVERED : enter / record remote if unset
        DISCOVERED : enter / emit discovery
        DISCOVERED : exit / emit isl-down

        [*] --> PRODUCE
        PRODUCE --> PUSH : discovery-timer
        PRODUCE : enter / raise discovery-timer

        PUSH --> CONFIRM_PUSH : confirmed
        PUSH --> FAIL_PUSH : push-fail-timer
        PUSH --> FAIL_PUSH : push-fail
        PUSH : enter / raise push-fail-timer
        PUSH : enter / send discovery packet
        PUSH : exit / cancel push-fail-timer

        CONFIRM_PUSH --> PRODUCE : next
        CONFIRM_PUSH : enter / emit push-discovery

        FAIL_PUSH --> PRODUCE : next
        FAIL_PUSH : enter / emit push-fail

        ||

        state checkMoved <<choice>>

        [*] --> MAIN
        
        MAIN --> checkMoved : discovery
        MAIN --> PROXY : discovery-pushed

        checkMoved --> CONFIRM_DISCOVERY : if same remote
        checkMoved --> MOVED : if remote changed

        PROXY --> MAIN : next
        PROXY : enter / emit discovery-pushed

        MOVED --> CONFIRM_DISCOVERY : next
        MOVED : enter / emit isl-move
        MOVED : enter / record remote

        CONFIRM_DISCOVERY --> MAIN : next
        CONFIRM_DISCOVERY : enter / emit discovery
    }
    DISCOVERED --> DOWN : port-down
}

OPERATIONAL --> BECOME_OFFLINE : offline
OPERATIONAL --> BECOME_DISABLED : disable
OPERATIONAL --> BECOME_UNMANAGED : port-unmanaged

BECOME_OFFLINE --> UNOPERATIONAL : next
BECOME_OFFLINE : enter / set online = false

BECOME_DISABLED --> UNOPERATIONAL : next
BECOME_DISABLED : enter / set enabled = false
BECOME_DISABLED : enter / emit isl-disable if have remote

BECOME_UNMANAGED --> UNOPERATIONAL : next
BECOME_UNMANAGED : enter / set managed = false
BECOME_UNMANAGED : enter / emit isl-unmanaged if have remote

state UNOPERATIONAL {
    [*] --> PENDING

    state OPERATIONAL_DECISION <<choice>>

    PENDING --> OPERATIONAL_DECISION : online (set online = true)
    PENDING --> OPERATIONAL_DECISION : offline (set online = false)
    PENDING --> OPERATIONAL_DECISION : disable (set enabled = false)
    PENDING --> OPERATIONAL_DECISION : enable (set enabled = true)
    PENDING --> OPERATIONAL_DECISION : port-unmanaged (set managed = false)
    PENDING --> OPERATIONAL_DECISION : port-managed (set managed = true)

    OPERATIONAL_DECISION --> PENDING : next
    OPERATIONAL_DECISION -u-> OPERATIONAL : next
}

@enduml
