@startuml
[*] --> INIT

state switchSync <<choice>>

INIT --> prepopulate : HISTORY
INIT --> setup : managed
INIT --> setup : online
INIT --> offline : offline

prepopulate : enter / fill port-list
prepopulate : enter / setup port workers
prepopulate : enter / setup ISL workers
prepopulate --> INIT : next

switchSync --> setup : is-online
switchSync --> offline : is-offline

setup : enter / [setup portWorker for portsAdded()]
setup : enter / [emit online for portAll()]
setup : enter / [emit port-del for portsRemoved()]
setup : enter / [emit port-down for portsBecomeDown()]
setup : enter / [emit port-up for portsBecomeUp()]
setup --> online : next

state online {
    [*] --> ONLINE_PENDING
    
    ONLINE_PENDING --> PORT_ADD : port-add
    ONLINE_PENDING --> PORT_DEL : port-del
    ONLINE_PENDING --> PORT_PROXY : port-up
    ONLINE_PENDING --> PORT_PROXY : port-down
    ONLINE_PENDING --> ISL_PROXY : discovery

    PORT_ADD : enter / add port to port-list
    PORT_ADD : enter / setup port worker
    PORT_ADD --> ONLINE_PENDING : next
    
    PORT_DEL : enter / kill port worker
    PORT_DEL : enter / remove port from port-list
    PORT_DEL --> ONLINE_PENDING : next

    PORT_PROXY --> ONLINE_PENDING : next
    ISL_PROXY --> ONLINE_PENDING : next
}
online --> offline : offline
online --> unmanaged : unmanaged

offline : enter / [emit offline for portAll()]
offline --> setup : online

unmanaged : enter / emit port-unmanaged [all ports]
unmanaged : exit / emit port-managed [all ports]
unmanaged --> switchSync : managed

@enduml
