@startuml
[*] --> INIT

state switchSync <<choice>>

INIT --> prepopulate : HISTORY
INIT --> setup : managed
INIT --> setup : online
INIT --> offline : offline

prepopulate : setup port workers
prepopulate : setup ISL workers
prepopulate --> INIT : next

switchSync --> setup : is-online
switchSync --> offline : is-offline

setup : enter / [setup portWorker for portsAdded()]
setup : enter / [emit online for portAll()]
setup : enter / [emit port-del for portsRemoved()]
setup : enter / [emit port-down for portsBecomeDown()]
setup : enter / [emit port-up for portsBecomeUp()]
setup --> online : next

state online {
    online : enter / set sw online = true
    online : exit / set sw online = false
    [*] --> ONLINE_PENDING
    
    ONLINE_PENDING --> PORT_ADD : port-add
    ONLINE_PENDING --> PORT_DEL : port-del
    ONLINE_PENDING --> PORT_PROXY : port-up
    ONLINE_PENDING --> PORT_PROXY : port-down

    PORT_ADD : setup port worker
    PORT_ADD : emit port-add
    PORT_ADD --> ONLINE_PENDING : next
    
    PORT_DEL : emit port-del
    PORT_DEL --> ONLINE_PENDING : next

    PORT_PROXY --> ONLINE_PENDING : next
}
online --> offline : offline
online --> unmanaged : unmanaged

offline : enter / [emit offline for portAll()]
offline --> setup : online

unmanaged : enter / set sw state unmanaged
unmanaged : enter / emit port-unmanaged [all ports]
unmanaged : exit / set sw state managed
unmanaged : exit / emit port-managed
unmanaged --> switchSync : managed

@enduml
